### ISSUE TITLE
(TM Beta 4.12.6121) if you set: Appearance | Layout | `Default - Darker` then for scripts that have a second row (menu command) both their lines appear truncated

### ISSUE THREAD

**Issue by darkred** [Tampermonkey/tampermonkey#1067]
Using TM beta 4.12.6121 in Chrome 86/Firefox 82 with Win10.

if you set Appearance|Layout|`Default - Darker` 
then for scripts that have a second row (menu command) both their lines appear truncated.

STR
In fresh TM beta installation, just install e.g. [this script](https://github.com/tophf/mpiv/raw/master/script.user.js) then reload any page. 
Here is screenshot comparison:
previous (4.11.6120) vs current (4.12.6121) version :
![2020-11-10_200819](https://user-images.githubusercontent.com/723651/98713658-8e06b880-2390-11eb-8794-0854c50a8c0d.jpg) 
![2020-11-10_200840](https://user-images.githubusercontent.com/723651/98713671-90691280-2390-11eb-952c-dfe6d6e8e2ed.jpg)

**Comment by 93Akkord** [comment]
Having the same issue here as well.  This bug also makes it so your unable to click the toggle button next to the script to enable/disable.

**Comment by narcolepticinsomniac** [comment]
Missed this issue when I was here recently. Darker theme is fixed [here](https://github.com/Tampermonkey/tampermonkey-layout/). I imagine it'll be included in the next beta.

If you guys run into issues before I see them in the future, ping me and I'll probably get around to it sooner.

**Comment by darkred** [comment]
@narcolepticinsomniac 
Thank you for the fix!

How may I apply the fixed code?
I tried copy-pasting the code from https://raw.githubusercontent.com/Tampermonkey/tampermonkey-layout/master/default/darker.css
into the textbox: `Appearance | Custom CSS`
and changed the layout to `Default - Darker`
but the issue remains.

**Comment by narcolepticinsomniac** [comment]
>I tried copy-pasting... to custom CSS.

That ain't gonna work, unfortunately. Too much conflicting code.

Other than waiting for the update, I could give you a zip of the version I side-load to work on. Side-loading only really works in Chromium, and even then, it might be a PITA to swap over, unless you're really impatient about it.

**Comment by darkred** [comment]
No, ok, I'll wait for the next TM beta version.
Thank you for the detailed reply.

**Comment by derjanb** [comment]
Should be fixed at the latest beta. @narcolepticinsomniac thanks for helping out here.

**Comment by darkred** [comment]
I confirm it's fixed in new beta with Chrome/Firefox.
Thank you both.
