### ISSUE TITLE
Script page load slow down messages persists even after the script is loaded

### ISSUE THREAD

**Issue by dnknn** [Tampermonkey/tampermonkey#1187]
> Sys:  Win10、 Chromium80-89 (tested+verified) 、Tampermonkey all versions(stable&beta) (at least 1 year)

## 💥 2 fatal problems caused by using Tampermonkey as UserJS/scripts container :
　　①. On some pages, it will cause a significant performance drop (very high CPU-usage), and some even crash (it takes ⩾8s~90s to complete load ), during this period, other normal pages will also fail to open.
　　②. On some pages, scripts cannot be excluded(`// @exclude`	) at all,  even the script is disabled, and even delete to the trash/recycle-bin,  still cannot be ruled out.

The above two problems should be directly related. can skip this floor and look directly at the test example below and the test comparison of Violentmonkey : 

👉 https://github.com/Tampermonkey/tampermonkey/issues/1187#issuecomment-804521668
👉 https://github.com/Tampermonkey/tampermonkey/issues/1187#issuecomment-805264334
👉 https://github.com/Tampermonkey/tampermonkey/issues/1187#issuecomment-812256520

　
　
---------------------------------

# 🗣 important statement: 
-  This fatal problem exists in both the Tampermonkey [stable](https://chrome.google.com/webstore/detail/dhdgffkkebhmkfjojejmpbldmpobfkfo) version and the [beta](https://chrome.google.com/webstore/detail/gcalenpjmijncebpfijmoaglllgpjagf) version (to be exact, it should have existed for at least 1 year)
- The URL page and script for the test are provided below, just as an example, In fact, I personally think that there is no problem with the page and the script code itself, because this problem can be encountered on many pages. 
- I have tested/verified/compared repeatedly, and I am pretty sure that it has nothing to do with the URL page or the script code. The only reason is the bug in the Tampermonkey container itself.

> sorry for my English..... and I don't know the code very well either, But the problem to be said below is indeed a very fatal problem, 

--------------------------------------------------------

>  💥 This fatal problem manifested as: 

## The root cause is: It is completely impossible to prevent the script from being executed on a certain page, so: 
- On some pages, the opening speed becomes abnormally slow, and at the same time, the CPU usage rises rapidly, which eventually leads to a significant drop in browser and system performance.
- If you have one or two hundred scripts installed (⚠Of course, there are at most 10 running on a page), At this time, it is almost impossible to open the page, I have encountered it for up to 1 minute...
- Of course, most pages do not have this problem, but many pages have this script. Even if I disable all the scripts, the problem still exists, unless Tampermonkey is disabled to solve this problem.

--------------------------------------------------------

#  For example: 
- URL page to testing:　https://item.taobao.com/item.htm?id=602809430649
- UserJS:  https://greasyfork.org/scripts/381682
- or  https://greasyfork.org/scripts/4255
> Just an example.

1. Then I tried to exclude the script not working on this page, but the results are all invalid...

	`*taobao*`
	
![image](https://user-images.githubusercontent.com/10995302/111925064-39174380-8ae2-11eb-9eaa-214c034085fe.png)

![213_22055350](https://user-images.githubusercontent.com/10995302/111923584-e1c1a500-8ada-11eb-9bd9-c75cd1f7e354.png)

2. Yes, I also added the URL of the iframe, but still cannot be ruled out.

	`/.*(?:aliapp|alibaba|alicdn|aliyun|aliyuncs|effirst|mmstat|tbcdn).+/`

3. So I tried to disable/OFF the script, but it still doesn't work.

4. Finally, I even tried to delete the script and temporarily put it in the 🗑Recycle Bin (beta version). Even if I delete it to the Recycle Bin, the script is still working...
![1](https://user-images.githubusercontent.com/10995302/111923575-db332d80-8ada-11eb-911e-49c77b6b959f.png)

---------------------------------

> After recording, I intentionally reduced the size of the gif (too big)

![gif22](https://user-images.githubusercontent.com/10995302/111924314-d2dcf180-8ade-11eb-8e96-afa965be2189.gif)

Therefore, I think it is not a script code problem (I encounter a very simple code that does not have any problems also have this problem), so this is completely a bug in the Tampermonkey container.

------------------------------------------------------

@derjanb I have sent the configuration of Tampermonkey and  100+ scripts to your 📧mail. You can reproduce the problem in 5 minutes.

1. Import the Tampermonkey script. (30 seconds)
2. Open several sample URL pages provided. (The problem can be reproduced immediately)
　　You will find that [the page](https://item.taobao.com/item.htm?id=602809430649) can hardly be opened, and the CPU usage is very high, (Tampermonkey's own page also froze and couldn't be opened.)
3. Hope can investigate this problem carefully. When you encounter this fatal problem, there is currently no any way except to disable the Tampermonkey extension... so hope to fix this problem first.

----

### Finally, the test content:  

> Why does it cause a significant drop in performance?
> What is terrible is that it is impossible to exclude scripts for such pages.
> 

1. Why is the script of the page excluded, even after the script is deleted to the recycle bin, the script is still executed in the background?

2. Why the script code itself has no problem, but it will cause performance crash on some pages, why?
Because I used `Violentmonkey` for the same test, there is no such performance problem and the problem that cannot be eliminated.

**Comment by dnknn** [comment]
# Supplementary comparison testing video :

> 🗣 Using [Violentmonkey](https://chrome.google.com/webstore/detail/opokoaglpekkimldnlggpoagmjegichg) as the script container, there is no problem, which means that there is no problem with the script code.

- Install 3 scripts :
https://greasyfork.org/scripts/372673
https://greasyfork.org/scripts/381682
https://greasyfork.org/scripts/4255

- Page to test performance :
https://item.taobao.com/item.htm?id=602809430649

![Violentmonkey](https://user-images.githubusercontent.com/10995302/112075814-2ff6a700-8bb4-11eb-9dc9-c599d9864850.gif)

With 3 scripts enabled, there is almost no impact on performance, and the loading completion time is only `0.3s` longer (1.25s -> 1.55s)

----------------------------------------------------------------------------
@derjanb 
⚔ Under the same test environment, use `Tampermonkey` as a script container, Tampermonkey will cause page performance crash, high CPU usage, Once encounter a page like this that causes performance, all pages cannot respond to network requests, and the page cannot be opened in a short time.

So I hope that the most deadly root cause can be investigated, and it can be perfectly fixed!

**Comment by dnknn** [comment]
# Supplementary comparison testing video :

> 🗣 Using [Violentmonkey](https://chrome.google.com/webstore/detail/opokoaglpekkimldnlggpoagmjegichg) as the script container, there is no problem, which means that there is no problem with the script code.

- Install 3 scripts :
https://greasyfork.org/scripts/372673
https://greasyfork.org/scripts/381682
https://greasyfork.org/scripts/4255

- Page to test performance :
https://item.taobao.com/item.htm?id=602809430649

　
## ⚔ Page performance test video of `Violentmonkey` :
![Violentmonkey](https://user-images.githubusercontent.com/10995302/112075814-2ff6a700-8bb4-11eb-9dc9-c599d9864850.gif)

　

With 3 scripts enabled, there is almost no impact on performance, and the loading completion time is only `0.3s` longer (1.25s -> 1.55s)

----------------------------------------------------------------------------
@derjanb 
Under the same test environment, use `Tampermonkey` as a script container, Tampermonkey will cause page performance crash, high CPU usage, Once encounter a page like this that causes performance, all pages cannot respond to network requests, and the page cannot be opened in a short time.

　
## ⚔ Page performance test video of `Tampermonkey` :
⚠: The test here only installs 3 scripts, and the speed affects `2s` (1.25s -> 3.1s). If the user installs ⩾ dozens of scripts (but not enabled), it will take at least 30s to respond at this time, and the page will crash during the period, and other pages will not be opened. .
![Tampermonkey](https://user-images.githubusercontent.com/10995302/112079834-ce3a3b00-8bbb-11eb-96d8-5a530af88c74.gif)

　

So I hope that the most deadly root cause can be investigated, and it can be perfectly fixed!

**Comment by dnknn** [comment]
I even forgot, recommend a perfect _open source_ & _lightweight_ extension, a very useful/convenient testing tool:

- ### Page load time 　　https://chrome.google.com/webstore/detail/fploionmjgeclbkemipmkogoaohcdbig

> This time value is consistent with the time in DevTools.

![213_23171458](https://user-images.githubusercontent.com/10995302/112122508-51c74c80-8bfb-11eb-8293-a8ad407e164a.png)

**Comment by dnknn** [comment]
I even forgot, recommend a perfect _open source_ & _lightweight_ extension, a very useful/convenient testing tool:

- ### Page load time 　　https://chrome.google.com/webstore/detail/fploionmjgeclbkemipmkogoaohcdbig

> This time value is consistent with the time in DevTools.

![image](https://user-images.githubusercontent.com/10995302/112126478-745b6480-8bff-11eb-9ff2-e858dbf5cb3f.png)


---------------------------------------------------------------------

# 🗣 It can be seen that `Violentmonkey` has almost no effect 👇!

> The same test environment, the same number of scripts and the number of runs.

![image](https://user-images.githubusercontent.com/10995302/112218890-44dc4480-8c5f-11eb-89ae-615900e734d2.png)

**Comment by dnknn** [comment]
@derjanb Hello! Can you investigate the root cause of this fatal problem in depth? 
This problem is very serious, it affects normal use too much ...... -_-

**Comment by dnknn** [comment]
@derjanb Hello! 

- I don't know if you confirm the fatal problem?

- Can you investigate the root cause of this fatal problem in depth? 
This problem is very serious, it affects normal use too much ...... -_-

**Comment by derjanb** [comment]
Should be fixed at the latest [BETA version](https://www.tampermonkey.net/crx/tampermonkey_beta_4_13_6133.crx) which will be published at the Chrome Web Store after review.

**Comment by dnknn** [comment]
> Should be fixed at the latest [BETA version](https://www.tampermonkey.net/crx/tampermonkey_beta_4_13_6133.crx)


@derjanb  First, thanks very much for your contribution in the fixed works, when I saw your reply message, I was very happy, I also looked at [the update log](https://www.tampermonkey.net/changelog.php?version=4.13.6133&ext=gcal&updated=true).
But.....no...no......no.... I was disappointed after the test...this very very fatal/serious problems still exist...
Please see picture below, it is very intuitive to see the severity/fatality of the problem.

![214_02081745](https://user-images.githubusercontent.com/10995302/113366485-eb28f800-938b-11eb-8b40-dec13341a558.png)

From the perspective of page completion time alone, from `1.0s` to `21s`, this problem is very serious.
For comparison, Violentmonkey's time is `1.3s` (extending 300ms is normal) (working 10 of 200 UserJS ). so obviously the UserJS code itself has no performance issues.


> The original speed of this page is actually `⩽1s` when opened under the cache, 
> before opening DevTools <Network>, it will affect about 0.3s.

# Test / Demo :

> ⚠Please Note⚠: You must be enough scripts (dozens or ≋ 200) to reproduce the problem.

1) Helper/assistant: 　Page load time [chrome.google.com/webstore/](https://chrome.google.com/webstore/detail/fploionmjgeclbkemipmkogoaohcdbig)	(very convenient to view page/DOM time)

2) Test page:  　　https://item.taobao.com/item.htm?id=602809430649

3) You must be enough scripts (e.g. dozens or ≋ 200) to reproduce the problem (You can find the 100 scripts I sent you before in your mailbox)

### ⚠⚠Please Note⚠⚠: You must be enough scripts (dozens or ≋ 200) to reproduce the problem.

> The latest version seems to have improved a little: 
> if it is the above 3 UserJS, the page time is `≋2.2s`, but it extended by `1.2s`, which is obviously problematic.
> But if your Tampermonkey has a sufficient number of scripts, then this time impact will be significantly extended, such as `21s` !!! -_- 

>PS: personal point of view: the features of Tampermonkey is already very powerful, so I think the focus of works should be on the direction of improving performance.

sorry for my English.......I don't know if you can understand the meaning....

**Comment by dnknn** [comment]
> Should be fixed at the latest [BETA version](https://www.tampermonkey.net/crx/tampermonkey_beta_4_13_6133.crx)


@derjanb  First, thanks very much for your contribution in the fixed works, when I saw your reply message, I was very happy, I also looked at [the update log](https://www.tampermonkey.net/changelog.php?version=4.13.6133&ext=gcal&updated=true).
But.....no...no......no.... I was disappointed after the test...this very very fatal/serious problems still exist...
Please see picture below, it is very intuitive to see the severity/fatality of the problem.

![214_02081745](https://user-images.githubusercontent.com/10995302/113366485-eb28f800-938b-11eb-8b40-dec13341a558.png)

> The original speed of this page is actually `⩽1s` when opened under the cache, 
> before opening DevTools \<Network\>, it will affect about 0.3s.

From the perspective of page completion time alone, from `1.0s` to `21s`, this problem is very serious.
For comparison, Violentmonkey's time is `1.3s` (extending 300ms is normal) (working 10 of 200 UserJS ). 
> ps: Violentmonkey's time may also be  `1.1s` or `1.2s` (I did not test Violentmonkey again this time, but was a complete test before.)
so obviously the UserJS code itself has no performance issues.



# Test / Demo :

> ⚠Please Note⚠: You must be enough scripts (dozens or ≋ 200) to reproduce the problem.

1) Helper/assistant: 　Page load time [chrome.google.com/webstore/](https://chrome.google.com/webstore/detail/fploionmjgeclbkemipmkogoaohcdbig)	(very convenient to view page/DOM time)

2) Test page:  　　https://item.taobao.com/item.htm?id=602809430649
>ps: This page is the most influential page I know, `21s`, so it is the best test sample.
>There are also many other pages that will be affected by performance, but it may be extended by about `3s`, `5s`, or `10s`.

3) You must be enough scripts (e.g. dozens or ≋ 200) to reproduce the problem (You can find the 100 scripts I sent you before in your mailbox)

4) Reproduce this `21s` fatal performance problem.....-_-

### ⚠⚠Please Note⚠⚠: You must be enough scripts (dozens or ≋ 200) to reproduce the problem.

> The latest version seems to have improved a little: 
> if it is the above 3 UserJS, the page time is `≋2.2s`, but it extended by `1.2s`, which is obviously problematic.
> But if your Tampermonkey has a sufficient number of scripts, then this time impact will be significantly extended, such as `21s` !!! -_- 

>PS: personal point of view: the features of Tampermonkey is already very powerful, so I think the focus of works should be on the direction of improving performance.

sorry for my English.......I don't know if you can understand the meaning....

**Comment by dnknn** [comment]
Hi, @derjanb !
- I would like to ask, have you **confirmed** this serious performance problem?
And did you find a solution?

> - I have encountered this serious problem on quite a few pages: the opening is slow, or even almost impossible to open, which makes me very sad.
If I disable Tampermonkey or using Violentmonkey, the page opens successfully in an instant.

- In these pages, enable Tampermonkey, and then even if all UserJS in Tampermonkey is disabled, it still opens slowly (or cannot be opened). 
- This shows that there are 2 logical problems:
  * UserJS cannot be really disabled (deleting to the recycle bin is the same)
  * It seems that there is a loophole in the loop? Causes the page to be unresponsive?
Because on these pages, I used Violentmonkey as a comparative test and found:
In Violentmonkey, even if you enable 50 UserJS for a page at the same time (`js` itself has no performance problems), it will have almost no impact on the page.

- So, can you give priority to investigating this big problem? 
Because currently Tampermonkey will not only cause some normal pages to fail to open, but also the CPU utilization rate will increase rapidly, and then any other pages will not be able to be opened in a short time. (If you want to be short (The only way to open other pages within time is to disable Tampermonkey and then enable)

**Comment by derjanb** [comment]
Yes, this message persists for 5 minutes even if the script is deleted in the meantime. However, the script is not executed or even considered for execution anymore.

So yes, there is a problem, but only a cosmetic one.

**Comment by dnknn** [comment]
@derjanb I guess that the fatal problem of this issue may be related to this problem 👇 ?

- I often encounter the problem of `@exclude` or `@include`, 
	 * The rules are obviously correct, but the result is completely ineffective!

- For example:  https://regex101.com/r/olMOpR/latest

```js
// @include		/(?:greasyfork|sleazyfork).org/.*/
// @include		/.*greasyfork.org.*/
// @include		/greasyfork.org/
```

**Comment by dnknn** [comment]
@derjanb I guess that the fatal problem of this issue may be related to this problem 👇 ?

- I often encounter the problem of `@exclude` or `@include`, 
	 * The rules are obviously correct, but the result is completely ineffective!

- For example:  https://regex101.com/r/olMOpR/latest

```js
// @include		/(?:greasyfork|sleazyfork).org/.*/
// @include		/.*greasyfork.org.*/
// @include		/greasyfork.org/
```

- Another example, 
	 * pages cannot be excluded, and metadata `// @noframes` cannot be excluded
	 * test-JS	 https://greasyfork.org/scripts/8736
	 	 * test-URL	 https://mail.163.com/

```js
// @noframes
		❌ invalid 
```

```js
// @exclude		*reg.163.com/*
// @exclude		*mail.163.com/*
		❌ invalid 
```

In the end, it still prompts that the script has been executed 6 times

> This code can quickly copy the URLs of all iframes embedded in the top page
```js
	// Copy all iframeURL
let ifrSrc = [];
top.document.querySelectorAll(`iframe:not([src='about:blank'])`).forEach(fE =>{
	ifrSrc.push(fE.src);
});
ifrSrc=Array.from(new Set(ifrSrc));
copy(ifrSrc.join(`\n`)+`\n`); console.log(`✔️copied: `+ifrSrc.length +`  iframeURLs`);
```

**Comment by derjanb** [comment]
Should be fixed at 5.3.6205 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
