### ISSUE TITLE
Firefox search hangs due to TamperMonkey DB access error

### ISSUE THREAD

**Issue by Pasrules** [Tampermonkey/tampermonkey#1921]
Expect to browse normally on Firefox (current-stable)

TamperMonkey (current-stable and current-beta) causing searching to take 30-40 seconds

Firefox debug shows 4x database access error

Found if firefox is set to "never remember history" to be the cause of the problem.

Recommend setting firefox to custom history setting "Clear history when Firefox closes"

![image](https://github.com/Tampermonkey/tampermonkey/assets/12654526/f174e818-3003-4a1e-a959-ab041d658470)

**Comment by derjanb** [comment]
Something prevents the [indexed DB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) from being opened. 

Please try a new browser profile. I guess it will work. Then adjust your browser settings step by step and check when it starts to fail.

Thanks.

**Comment by Pasrules** [comment]
> Something prevents the [indexed DB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) from being opened.
> 
> Please try a new browser profile. I guess it will work. Then adjust your browser settings step by step and check when it starts to fail.
> 
> Thanks.

I have done this.

>Found if firefox is set to "never remember history" to be the cause of the problem.

**Comment by derjanb** [comment]
Yes, sorry, I saw that too late. 

Please downgrade to 4.19 or disable the setting for now. I'll fix this soon.

External bug reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1427986

**Comment by jgoggan** [comment]
So, just to make sure I understand, this is caused by a 5+ year old bug in Firefox itself whose status is still "NEW", correct?  So this is very unlikely to be fixed any time soon on the Firefox side and, I assume, it can't be worked around on the TM side?

I guess the "workaround" is to put Firefox in Custom History mode instead of Never Remember mode -- and then set everything to not remember and to remove everything on close?

**Comment by derjanb** [comment]
I'll use another storage instead of indexed DB. So I'll fix it on my side.

**Comment by gbdomubpkm** [comment]
I am only sharing my experience, I am not a developer.
Before Last night on a Ubuntu 20.04 laptop and latest Firefox update: Connection to any web page extremely slow as if I had no internet speed (which I thought at first). Then I started to believe that it was the Firefox update that was faulty because the Vivaldi browser was working normally. Then yesterday afternoon, I started Firefox in minimum mode: it was working normally. Return to normal Firefox and deactivate tampermonkey and Firefox works normally (the problems arose suddenly after the last update of tampermonkey the day before last night). I temporarily uninstalled tampermonkey.

Do you confirm i had the issue opened here ?

Please could you tell me when  the next update of tampermonkey will take place in Firefox under Ubuntu?

Thank you for your work about this great app.

**Comment by IRainman** [comment]
I return to version 4.19 and now all fine, Firefox 120.0.1 Windows 10. Currently, I manually downgrade extension on many machines and this is definitely very hard to me. I completely disable updates for the extension and don't want to enable it again before this issue is completely fixed.

**Comment by derjanb** [comment]
> Please could you tell me when the next update of tampermonkey will take place in Firefox

I'm working on this. I hope to have a new BETA version this week.

**Comment by derjanb** [comment]
A new BETA is in review since 2023-12-14

**Comment by derjanb** [comment]
Should be fixed at 5.0.6191 ([xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

If possible, please also enable anonymous statistics because the sent crash reports help to detect issues earlier...

**Comment by proxie99** [comment]
Simply enabling History < Firefox will "Remember history" solves the problem across the board.. not sure why never Remembering History causes TamperM to lock up....

**Comment by derjanb** [comment]
> not sure why never Remembering History causes TamperM to lock up....

This is due to a Firefox bug that I wasn't aware of...
https://bugzilla.mozilla.org/show_bug.cgi?id=1427986

**Comment by gbdomubpkm** [comment]
Hello @derjanb 
Is there a close date planned for the next stable release or do big bugs still need to be fixed before then? Regards

**Comment by derjanb** [comment]
@gbdomubpkm A new release is already in review since Jan. 3, 2024

**Comment by derjanb** [comment]
5.0.1 which includes the fix is available here: https://addons.mozilla.org/de/firefox/addon/tampermonkey/

Sorry for any inconvenience!

**Comment by gbdomubpkm** [comment]
@derjanb Tested and i confirm the issue is fixed on Firefox on ubuntu 20.04. Thanks.
