### ISSUE TITLE
Firefox extension: Persistently creates new Google Authentication tabs

### ISSUE THREAD

**Issue by ohsospoko** [Tampermonkey/tampermonkey#1925]
(Please fill out the issue template with your details)

## Expected Behavior
With Google Drive sync enabled, TM will ask **once** for user to authenticate Google account. It may re-ask if the extension is restarted, etc.

## Actual Behavior
TM continuously generates new authentication requests, each in a new tab. If the browser is left idle for even an hour or two, dozens and dozens of new tabs will be opened solely for this.

## Specifications

- Firefox: 115.5.0esr
- TM: 5.0.0
- OS: Windows 10 Enterprise v. 22H2

**Comment by derjanb** [comment]
Since the background page now is an event page the extension in fact is restarted multiple times per hour... 

I'll check that. Thanks for reporting.

**Comment by UndarkAido** [comment]
It's causing absolutley bonkers stuff to happen in [filips123/PWAsForFirefox](https://github.com/filips123/PWAsForFirefox/), I just had it start spamming new empty windows when I sat down and I had to close it from the task manager

**Comment by derjanb** [comment]
@UndarkAido Please downgrade to 4.19.0 until the issue is fixed. Sorry for any inconvenience.

**Comment by jrom99** [comment]
> @UndarkAido Please downgrade to 4.19.0 until the issue is fixed. Sorry for any inconvenience.

I'm sorry if this is off-topic, but I don't know how to downgrade an extension in Firefox. Could you provide a how-to or a link with a tutorial to follow?

**Comment by UndarkAido** [comment]
To the best of my knowledge you go to the extensions's listing, click previous versions, download the file for the version you want, then install it manually from the manage extensions page.

**Comment by derjanb** [comment]
Yes, go to  https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/versions/
Scroll down to the version you want (4.19.0)
Click at download file and at least my Firefox then directly installs this version

**Comment by ohsospoko** [comment]
> Yes, go to https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/versions/ Scroll down to the version you want (4.19.0) Click at download file and at least my Firefox then directly installs this version

Thanks—this worked for me, though I had to try it twice for it to take.

**Comment by derjanb** [comment]
Should be fixed at 5.0.6191 ([xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by derjanb** [comment]
5.0.1 which includes the fix is available here: https://addons.mozilla.org/de/firefox/addon/tampermonkey/

Sorry for any inconvenience!

**Comment by bekoeppel** [comment]
I've just updated to version 5.0.1, restarted Firefox, but keep on getting the popup. 

    Firefox: 121.0 (64-bit)
    TM: v5.0.1
    OS: Ubuntu 20.04.6 LTS

**Comment by ohsospoko** [comment]
> I've just updated to version 5.0.1, restarted Firefox, but keep on getting the popup.
> 

Same. Ffx 115.6.0esr (64-bit). Windows 10 Enterprise 22H2.

**Comment by ohsospoko** [comment]
> 5.0.1 which includes the fix is available here: https://addons.mozilla.org/de/firefox/addon/tampermonkey/
> 
> Sorry for any inconvenience!

Upgraded to 5.0.1, but it's still happening. Might be less frequent, I'm not sure. But definitely still several times over a couple of hours.

**Comment by Martin-Milbradt** [comment]
Still happening for me:
```
Firefox 121.0.1 (64-bit)
Tampermonkey v5.0.6192
Windows 11 Version 10.0.22631 Build 22631
```

**Comment by derjanb** [comment]
Should finally be fixed at 5.1.6193 ([xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by derjanb** [comment]
5.1.6193 might still ask two times in the beginning, but should then hopefully ask never again. ;-)
You can speed this up, by revoking the token manually.

**Comment by jrom99** [comment]
Hello, I'm using the beta extension 5.1.6193 on Firefox 124.0 (OS Ubuntu 23.10). The bug went away after I installed it, but today it started creating new tabs again.

**Comment by derjanb** [comment]
Sorry, this was my fault. I needed to update the server and this caused the issue. Everybody that needed to refresh the token between "Mar 15 20:12:05 UTC" and now, might see another authentication tab... Sorry again.

@jrom99  Thank you very much for reporting!

**Comment by jrom99** [comment]
Is there any action that I need to do to stop it? Or will it stop by itself?

**Comment by derjanb** [comment]
@jrom99  You've found another bug. 🙈 I fixed that one as well, so after one more authentication dialog you should be fine again.
Sorry for any inconvenience and thanks for contentiously reporting issues.

**Comment by jrom99** [comment]
It has stopped, thanks!

**Comment by UndarkAido** [comment]
I'm on the beta, and not only does it open tons of tabs attempting to sign in results in this:
![image](https://github.com/Tampermonkey/tampermonkey/assets/7421794/1d05cf32-adf7-4e65-92ae-ccaa34c011dd)
And I accidentally deleted my years of scripts trying to troubleshoot. Should've made a backup, I'm such an idiot. I have the extension data from a Windows reinstall I did a couple of months ago but no clue how to extract it.

**Comment by jrom99** [comment]
Which version do you have installed? I'm on the beta as well and it does not happen here.

**Comment by UndarkAido** [comment]
Whatever the latest beta was yesterday, I gave up trying to make it work and uninstalled
