### ISSUE TITLE
Cannot install Tampermonkey Beta from chrome webstore

### ISSUE THREAD

**Issue by MWillberg** [Tampermonkey/tampermonkey#2076]
I'm not sure if this is Tampermonkey issue, maybe Google has broken something.

## Expected Behavior

The extension would install.

## Actual Behavior

When the extension web page is loaded there are already errors in the console

Error with Permissions-Policy header: Unrecognized feature: 'ch-ua-form-factor'.

https://chromewebstore.google.com/detail/tampermonkey-beta/gcalenpjmijncebpfijmoaglllgpjagf
gcalenpjmijncebpfijmoaglllgpjagf:1 Unchecked runtime.lastError: Invalid manifest
content.js:63 content: DOMContentLoaded
content.js:63 content: normal start event processing for lwsjk93l.5mt (2 to run)
content.js:63 content: load

When "add to chrome" is selected, a spinner appears and stays there forever. Console shows no additional messages.

## Specifications

- Chrome Version 125.0.6422.113 (Official Build) (64-bit)
- OS: Microsoft Windows [Version 10.0.19045.3693]

The same result happens with another computer and different google account.

Installation using CRX file works ok.

**Comment by derjanb** [comment]
Working fine here using Version 126.0.6478.26 and Version 125.0.6422.113

In the recent past I released a lot of versions partially. Maybe this caused the issue? Can you please re-test? The current BETA version is rolled out to 100% of all users...

**Comment by MWillberg** [comment]
Re-tested on the same pc and now the installation "add to chrome" confirmation dialog pops up. So now it works ok.

IN the console "Invalid manifest"  error has vanished, but "...Permissions-Policy header..." error is still there, along with few third-party cookie warnings, but they do not seem to have an effect to the installation issue.
