### ISSUE TITLE
[BUG] Context menu not appearing & Feature Request: Run from extension icon

### ISSUE THREAD

**Issue by ppo** [Tampermonkey/tampermonkey#2531]
### Bug

Sometimes a specific script doesn't appear in the Tampermonkey contextual menu. Usually trying another time (or several times) to reopen the contextual menu works.

Sometimes it's even the whole Tampermonkey menu that is not there. And in that case, I didn't find anything to do to fix that. Usually it's just temporary, sometimes opening a new tab with the same URL works. Sometimes it doesn't work at all until we reopen the browser.

When that happens, the scripts are well detected/listed in the extension toolbar (top-right pinned extension icons, next to address bar).

### Feature Request

Allow to execute `context-menu` scripts from the extension toolbar icon (top-right pinned extension icons, next to address bar).

**Comment by derjanb** [comment]
Should be fixed at 5.5.6234 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` or wait for the Chrome Web Store review being done.
Firefox users please wait for the XPI being reviewed and install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` **once the review is finished**.

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by ppo** [comment]
🤔 Is it normal that it's only v5.4.1 (November 21, 2025) in the Chrome Web Store?
https://chromewebstore.google.com/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo

**Comment by derjanb** [comment]
Yes, the stable version is updated after all changes are tested in the BETA version which can be found here: https://chromewebstore.google.com/detail/tampermonkey-beta/gcalenpjmijncebpfijmoaglllgpjagf

BETA 5.5.6234 however is still in review. You need to download the (signed) crx file to test the changes now.

**Comment by ppo** [comment]
I still have the same problem with the BETA version.
I've both installed (5.4.1 & 5.5.6234).
2 main problems in the contextual menu: some scripts not shown or the whole menu not shown.
I've seen probably all the combinations between the 2 versions (5.4 & 5.5) – only one working, or only partially, or both not working.
In the BETA version, in the pinned icon menu, sometimes the "execute now" disappears.
With BETA, when I execute a script, it disappears from the contextual menu and the "execute now" also.
