### ISSUE TITLE
[Firefox] narrow popup

### ISSUE THREAD

**Issue by Mottie** [Tampermonkey/tampermonkey#804]
(Please fill out the issue template with your details)

## Expected Behavior

Firefox popup should expand horizontally to allow for the selected number of columns to show

## Actual Behavior

The Firefox popup only shows the left-most and half of the second column, and none of the third column if set.

<img width="199" alt="2019-11-07 07_33_50-Github page gets stuck during loading · Issue #72 · StylishThemes_GitHub-Dark-Sc" src="https://user-images.githubusercontent.com/136959/68394194-0231cf00-0133-11ea-9214-c5ce7e9cf3fa.png">

## Specifications

- Firefox 70.0.1
- TM v4.9.5941
- OS: Window 10

## Script

N/A

**Comment by derjanb** [comment]
Hmm, I've never seen it that bad, but some other scroll issues. Can you please check whether the issue exists at Tampermonkey BETA 4.9.6088 https://firefox.tampermonkey.net/firefox-current-beta.xpi ?
Thanks.

**Comment by Mottie** [comment]
Yeah, it looks like it's fixed in beta

![](https://user-images.githubusercontent.com/136959/68536227-5cce5500-0304-11ea-9207-47a5a3056227.png)

**Comment by derjanb** [comment]
Great news. 😅

**Comment by derjanb** [comment]
Unfortunately, the fix had some pages effect. can you confirm that the problem in version Tampermonkey BETA 4.10.6100 (https://www.tampermonkey.net/index.php?browser=firefox) is still fixed?

**Comment by Mottie** [comment]
I can't download that beta version, Firefox says it's unsigned.

![](https://user-images.githubusercontent.com/136959/69199072-910ff580-0afc-11ea-80a9-f160917a07e0.png)

**Comment by derjanb** [comment]
It should work now. :)

**Comment by Mottie** [comment]
Sadly, it's still an issue in 4.10.6100.

**Comment by derjanb** [comment]
Please re-open if this still an issue. Thanks.

**Comment by Mottie** [comment]
I'm still seeing this issue with FF 75.0 (64-bit) & TM 4.10.6112 when I set the set the action menu to more than one column. I don't use FF that much, so it's not a huge deal.

One additional note: I am using Firefox on a 4K monitor.
